# Replace identityHash values with real ones before applying
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: apiexport
spec:
  permissionClaims:
    - group: ""
      resource: "secrets"
    - group: ""
      resource: "configmaps"
    - group: ""
      resource: "namespaces"
    - group: ""
      resource: "events"
    - group: ""
      resource: "serviceaccounts"
    - group: "tekton.dev"
      resource: "pipelineruns"
      # Replace by pipeline-service identityHash
      identityHash: pipeline-service
    - group: "appstudio.redhat.com"
      resource: "components"
      # Replace by application-api identityHash
      identityHash: application-api
    - group: "appstudio.redhat.com"
      resource: "applications"
      # Replace by application-api identityHash
      identityHash: application-api
